// Generated by components discovery
declare module 'vue' {
  export interface GlobalComponents {
    'AdicionarDespesa': typeof import("../components/AdicionarDespesa.vue")['default'],
    'AdicionarEntrada': typeof import("../components/AdicionarEntrada.vue")['default'],
    'Auth': typeof import("../components/Auth.vue")['default'],
    'Calculoplantio': typeof import("../components/Calculoplantio.vue")['default'],
    'Component': typeof import("../components/component.vue")['default'],
    'NuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default'],
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/layout")['default'],
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default'],
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default'],
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default'],
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default'],
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyAdicionarDespesa': typeof import("../components/AdicionarDespesa.vue")['default'],
    'LazyAdicionarEntrada': typeof import("../components/AdicionarEntrada.vue")['default'],
    'LazyAuth': typeof import("../components/Auth.vue")['default'],
    'LazyCalculoplantio': typeof import("../components/Calculoplantio.vue")['default'],
    'LazyComponent': typeof import("../components/component.vue")['default'],
    'LazyNuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default'],
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/layout")['default'],
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default'],
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default'],
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default'],
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default'],
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
  }
}

export const AdicionarDespesa: typeof import("../components/AdicionarDespesa.vue")['default'],
export const AdicionarEntrada: typeof import("../components/AdicionarEntrada.vue")['default'],
export const Auth: typeof import("../components/Auth.vue")['default'],
export const Calculoplantio: typeof import("../components/Calculoplantio.vue")['default'],
export const Component: typeof import("../components/component.vue")['default'],
export const NuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default'],
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/layout")['default'],
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default'],
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default'],
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default'],
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default'],
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyAdicionarDespesa: typeof import("../components/AdicionarDespesa.vue")['default'],
export const LazyAdicionarEntrada: typeof import("../components/AdicionarEntrada.vue")['default'],
export const LazyAuth: typeof import("../components/Auth.vue")['default'],
export const LazyCalculoplantio: typeof import("../components/Calculoplantio.vue")['default'],
export const LazyComponent: typeof import("../components/component.vue")['default'],
export const LazyNuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default'],
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/layout")['default'],
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default'],
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default'],
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default'],
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default'],
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']

export const componentNames: string[]
